
& "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0ARtbsJq5I4OArswtsz5I_vv54CbIQxbUvyeYmAGRU9dhHvpgwAM_tT1m_5mgA3Q7FswuDQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
